// Builds src/data/stars.json from a small catalog of real nearby stars (J2000 right ascension / declination and
// distance in light years, rounded). Positions are heliocentric equatorial x/y/z in light years.
// Beacons: four symmetric (tetrahedral) directions around the Sun at BEACON_LY, each snapped to the nearest real star.
// Usage: node tools/build-stars.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// id, name, RA (h m s), Dec (deg), distance ly, spectral class
const CATALOG = [
  ['sol', 'SOL', [0, 0, 0], 0, 0, 'G2V'],
  ['proxima', 'PROXIMA CENTAURI', [14, 29, 43], -62.68, 4.24, 'M5.5V'],
  ['alpha-cen', 'ALPHA CENTAURI', [14, 39, 36], -60.83, 4.37, 'G2V'],
  ['barnard', "BARNARD'S STAR", [17, 57, 48], 4.69, 5.96, 'M4V'],
  ['wolf-359', 'WOLF 359', [10, 56, 29], 7.01, 7.86, 'M6V'],
  ['lalande-21185', 'LALANDE 21185', [11, 3, 20], 35.97, 8.31, 'M2V'],
  ['sirius', 'SIRIUS', [6, 45, 9], -16.72, 8.6, 'A1V'],
  ['luyten-726-8', 'LUYTEN 726-8', [1, 39, 1], -17.95, 8.73, 'M5.5V'],
  ['ross-154', 'ROSS 154', [18, 49, 49], -23.84, 9.69, 'M3.5V'],
  ['ross-248', 'ROSS 248', [23, 41, 55], 44.18, 10.3, 'M5.5V'],
  ['epsilon-eridani', 'EPSILON ERIDANI', [3, 32, 56], -9.46, 10.5, 'K2V'],
  ['lacaille-9352', 'LACAILLE 9352', [23, 5, 52], -35.85, 10.7, 'M0.5V'],
  ['ross-128', 'ROSS 128', [11, 47, 44], 0.8, 11.0, 'M4V'],
  ['ez-aquarii', 'EZ AQUARII', [22, 38, 33], -15.3, 11.1, 'M5V'],
  ['61-cygni', '61 CYGNI', [21, 6, 54], 38.75, 11.4, 'K5V'],
  ['procyon', 'PROCYON', [7, 39, 18], 5.22, 11.46, 'F5IV'],
  ['struve-2398', 'STRUVE 2398', [18, 42, 47], 59.63, 11.5, 'M3V'],
  ['groombridge-34', 'GROOMBRIDGE 34', [0, 18, 23], 44.02, 11.6, 'M1.5V'],
  ['dx-cancri', 'DX CANCRI', [8, 29, 49], 26.78, 11.8, 'M6.5V'],
  ['epsilon-indi', 'EPSILON INDI', [22, 3, 22], -56.79, 11.87, 'K5V'],
  ['tau-ceti', 'TAU CETI', [1, 44, 4], -15.94, 11.9, 'G8V'],
  ['gj-1061', 'GJ 1061', [3, 36, 0], -44.51, 12.0, 'M5.5V'],
  ['yz-ceti', 'YZ CETI', [1, 12, 31], -16.99, 12.1, 'M4.5V'],
  ['luytens-star', "LUYTEN'S STAR", [7, 27, 24], 5.23, 12.2, 'M3.5V'],
  ['teegarden', "TEEGARDEN'S STAR", [2, 53, 1], 16.88, 12.5, 'M7V'],
  ['kapteyn', "KAPTEYN'S STAR", [5, 11, 41], -45.02, 12.8, 'M1V'],
  ['lacaille-8760', 'LACAILLE 8760', [21, 17, 15], -38.87, 12.9, 'M0V'],
  ['kruger-60', 'KRUGER 60', [22, 27, 59], 57.7, 13.1, 'M3V'],
  ['altair', 'ALTAIR', [19, 50, 47], 8.87, 16.7, 'A7V'],
  ['eta-cassiopeiae', 'ETA CASSIOPEIAE', [0, 49, 6], 57.82, 19.4, 'G0V'],
  ['82-eridani', '82 ERIDANI', [3, 19, 56], -43.07, 19.7, 'G8V'],
  ['delta-pavonis', 'DELTA PAVONIS', [20, 8, 44], -66.18, 19.9, 'G8IV'],
  ['vega', 'VEGA', [18, 36, 56], 38.78, 25.0, 'A0V'],
  ['fomalhaut', 'FOMALHAUT', [22, 57, 39], -29.62, 25.1, 'A3V'],
  ['pollux', 'POLLUX', [7, 45, 19], 28.03, 33.8, 'K0III'],
  ['denebola', 'DENEBOLA', [11, 49, 4], 14.57, 36.0, 'A3V'],
  ['arcturus', 'ARCTURUS', [14, 15, 40], 19.18, 36.7, 'K1.5III'],
  ['capella', 'CAPELLA', [5, 16, 41], 45.99, 42.9, 'G3III'],
  ['castor', 'CASTOR', [7, 34, 36], 31.89, 51.0, 'A1V'],
  ['alderamin', 'ALDERAMIN', [21, 18, 35], 62.59, 49.0, 'A8V'],
  ['achernar', 'ACHERNAR', [1, 37, 43], -57.24, 139.0, 'B6V'],
  ['aldebaran', 'ALDEBARAN', [4, 35, 55], 16.51, 65.0, 'K5III'],
  ['regulus', 'REGULUS', [10, 8, 22], 11.97, 79.0, 'B8IV'],
  ['alphecca', 'ALPHECCA', [15, 34, 41], 26.71, 75.0, 'A1IV'],
];

const BEACON_LY = 38;
const r1 = (v) => Math.round(v * 100) / 100;

const stars = CATALOG.map(([id, name, [h, m, s], dec, ly, cls]) => {
  const ra = ((h + m / 60 + s / 3600) * 15) * Math.PI / 180, de = dec * Math.PI / 180;
  return { id, name, cls, ly, x: r1(ly * Math.cos(de) * Math.cos(ra)), y: r1(ly * Math.cos(de) * Math.sin(ra)), z: r1(ly * Math.sin(de)) };
});

// tetrahedron around the Sun, rotated so no vertex points straight at a catalog pole
const dirs = [[1, 1, 1], [1, -1, -1], [-1, 1, -1], [-1, -1, 1]].map((v) => v.map((c) => c / Math.sqrt(3)));
const taken = new Set();
const beacons = dirs.map((d) => {
  const p = d.map((c) => c * BEACON_LY);
  // only far stars qualify, so every beacon is a long trip (about a week of real time)
  const best = stars.filter((s) => s.ly >= 25 && s.ly <= 60 && !taken.has(s.id))
    .sort((a, b) => Math.hypot(a.x - p[0], a.y - p[1], a.z - p[2]) - Math.hypot(b.x - p[0], b.y - p[1], b.z - p[2]))[0];
  taken.add(best.id);
  best.beacon = true;
  return best.id;
});

const out = {
  _doc: 'Real nearby stars (generated by tools/build-stars.mjs; edit the catalog there). x/y/z = heliocentric equatorial position in light years, ly = distance from the Sun, cls = spectral class. beacon = one of four symmetric long-term goals.',
  beacons,
  stars,
};
fs.writeFileSync(path.join(root, 'src/data/stars.json'), JSON.stringify(out, null, 1) + '\n');
console.log(`stars: ${stars.length}, beacons: ${beacons.join(', ')}`);
