// Galaxy builder: src/data/stars.json (real stars) -> src/data/galaxy.gen.json
//   stars: 3D positions in light years (x toward RA 0h, z toward the north celestial pole), beacon flags
//   planets: one generated planet for every star without a hand-made planet in planets.json
// Deterministic: same input always gives the same galaxy. Run by `npm run sprites`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const { stars } = readJson('src/data/stars.json');
const { planets: handPlanets } = readJson('src/data/planets.json');
const travel = readJson('src/data/travel.json');

const round = (v) => Math.round(v * 100) / 100;
const hash = (s) => { let h = 2166136261; for (const c of s) h = Math.imul(h ^ c.charCodeAt(0), 16777619); return h >>> 0; };
const rng = (seed) => () => { seed = (seed + 0x6d2b79f5) | 0; let t = Math.imul(seed ^ (seed >>> 15), 1 | seed); t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t; return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };

// 1. positions
const out = stars.map((s) => {
  const ra = (s.ra / 24) * Math.PI * 2, dec = (s.dec / 180) * Math.PI;
  return { id: s.id, name: s.name, type: s.type, dist: s.dist,
    x: round(s.dist * Math.cos(dec) * Math.cos(ra)), y: round(s.dist * Math.cos(dec) * Math.sin(ra)), z: round(s.dist * Math.sin(dec)), beacon: false };
});

// 2. beacons: six symmetric points around Sol, each snapped to the nearest unused real star
const D = travel.beaconDistanceLy;
for (const [x, y, z] of [[D, 0, 0], [-D, 0, 0], [0, D, 0], [0, -D, 0], [0, 0, D], [0, 0, -D]]) {
  let best = null, bd = Infinity;
  for (const s of out) {
    if (s.id === 'sol' || s.beacon) continue;
    const d = Math.hypot(s.x - x, s.y - y, s.z - z);
    if (d < bd) { bd = d; best = s; }
  }
  best.beacon = true;
}

// 3. one generated planet per star (unless planets.json already has one for that star)
const ACCENTS = [[27, 28, 29], [16, 17, 18], [5, 4, 3], [6, 7, 8], [14, 13, 12], [0, 1, 2], [15, 14, 13], [22, 21, 20]];
const GROUNDS = [[25, 24, 23], [25, 15, 23], [25, 6, 23]];
const SKY = { M: ['181425', '3e2731', 'a22633'], K: ['181425', '733e39', 'd77643'], G: ['181425', '262b44', 'e4a672'],
  F: ['181425', '124e89', 'c0cbdc'], A: ['181425', '124e89', 'c0cbdc'], D: ['181425', '262b44', '8b9bb4'] };
const AMBIENT = { M: '5e4a70', K: '6e5a74', G: '6a6a90', F: '7a86b0', A: '7a86b0', D: '586488' };
const hand = new Set(handPlanets.map((p) => p.star));
const planets = [];
for (const s of out) {
  if (hand.has(s.id)) continue;
  const r = rng(hash(s.id));
  const pick = (a) => a[Math.floor(r() * a.length)];
  const int = (a, b) => a + Math.floor(r() * (b - a + 1));
  const cls = s.type[0];
  const enemies = { skitter: int(4, 9) };
  if (r() < 0.7) enemies.hopper = int(2, 6);
  planets.push({
    id: s.id,
    name: `${s.name} B`,
    subtitle: s.beacon ? 'BEACON' : `${s.dist} LIGHT YEARS FROM SOL`,
    star: s.id,
    planetIndex: 1,
    seed: hash(`${s.id}:1`) % 100000,
    accent: pick(ACCENTS),
    ground: pick(GROUNDS),
    ambient: AMBIENT[cls] ?? AMBIENT.G,
    sky: SKY[cls] ?? SKY.G,
    size: [int(88, 104), int(64, 80)],
    islandRadius: round(0.8 + r() * 0.1),
    rockThreshold: round(0.55 + r() * 0.11),
    ruins: int(1, 4),
    resourceNodes: s.beacon ? travel.beaconResourceNodes : int(12, 20),
    enemies,
    decorDensity: round(0.05 + r() * 0.05),
    sporeRate: int(1, 4),
    trees: r() < 0.2 ? 0.02 : 0,
    towers: 0,
    intro: 'land',
    beacon: s.beacon,
  });
}

fs.writeFileSync(path.join(root, 'src/data/galaxy.gen.json'), JSON.stringify({ _doc: 'Generated by tools/gen-galaxy.mjs from stars.json. Do not edit by hand.', stars: out, planets }, null, 1) + '\n');
console.log(`galaxy: ${out.length} stars, ${planets.length} generated planets, beacons: ${out.filter((s) => s.beacon).map((s) => s.name).join(', ')}`);
